#!/bin/sh

### BEGIN INIT INFO
# Provides:          synchronetbbs
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start SBBS at boot time
# Description:       Start SBBS at boot time
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

export SBBSDIR=/sbbs
case "$1" in

start)		echo "Starting SBBS... "
		if [ -f "$SBBSDIR/nostart" ]; then
			# Remove the lock file if it exists
			rm "$SBBSDIR/nostart"
		fi
		# Start the screen process
		nohup $SBBSDIR/startsynchronetbbs > /tmp/SBBSStartup.log&
		;;
stop)		echo "Stopping SBBS process... "
		touch "$SBBSDIR/nostart"
		killall sbbs
		exit 1
		;;
restart)        $0 stop
		rm "$SBBSDIR/nostart"
		#killall --user $USER sleep
                ;;
status)		running=`ps ax|grep sbbs|grep -v grep`
		if [ ! -z "$running" ]; then
			echo "SBBS Server Running"
		else
			echo "SBBS Server Not Running"
		fi
		;;
*)              echo "Usage: $0 {start|status|stop|restart}"
                exit 1
                ;;
esac
exit 0
