#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          synchronetbbs
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Synchronet BBS service 1.0
# Description:       Synchronet BBS service 1.0
# Documentation:     https://synchronetbbs.org/index.php/forum/alternate-startup-scripts
# Type:              forking
# PIDFile:           /sbbs/ctrl/sbbs.pid
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $SBBSDIR = "/sbbs";

my $Command = $ARGV[0];

my $running=`ps ax|grep sbbs|grep -v grep`;
chop($running);
$running = substr($running, -4);

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting SBBS...\n";
		if (-f "$SBBSDIR/nostart")
		{
			print "Removing $SBBSDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$SBBSDIR/nostart");
		}
		# Start the screen process
		system("nohup $SBBSDIR/startsynchronetbbs > /tmp/SBBSStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping SBBS process...\n";
	system("touch '$SBBSDIR/nostart'");
	if ($running eq "running")
	{
		system("killall sbbs");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$SBBSDIR/nostart")
	{
		print("Removing $SBBSDIR/nostart\n");
		unlink("$SBBSDIR/nostart");
	}
	if ($running eq "sbbs")
	{
		system("killall sbbs");
	}
}
elsif ($Command eq "status")
{
	if ($running eq "sbbs")
	{
		print("SBBS Server Running\n");
	}
	else
	{
		print("SBBS Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}");
	exit(1);
}

exit(0);
